insert into public.questions (slug, category, difficulty, prompt, instruction, unit, correct_answer, hint)
values
  ('growth-12m-25pct-2y', 'Growth projection', 1, 'Revenue is €12M and grows 25% annually. What is revenue after 2 years?', 'Enter the ending revenue after compounding both years.', '€M', 18.75, 'Find 25% by dividing by four. Year 1 reaches €15M; repeat on the new total.'),
  ('profit-240k-variable-60', 'Operating profit', 1, 'Net sales are €240k. Variable costs are 60% and fixed costs are €54k. What is operating profit?', 'Enter the resulting operating profit.', '€k', 42, 'Find 40% contribution first, then subtract fixed costs.'),
  ('margin-72-to-68', 'Margin impact', 1, 'Gross margin falls from 72% to 68% on €20M of revenue. How much gross profit is lost?', 'Enter the reduction in gross profit.', '€M', 0.8, 'Apply the four percentage-point change to €20M.'),
  ('growth-8m-20pct-2y', 'Growth projection', 1, 'Revenue is €8M and grows 20% annually. What is revenue after 2 years?', 'Enter the ending revenue.', '€M', 11.52, 'Multiply by 1.2 twice.'),
  ('growth-5m-10pct-3y', 'Growth projection', 2, 'Revenue is €5M and grows 10% annually. What is revenue after 3 years?', 'Enter the ending revenue.', '€M', 6.655, 'Compound by multiplying by 1.1 for each year.'),
  ('decline-10m-15pct', 'Growth projection', 1, 'Revenue is €10M and declines by 15%. What is the new revenue?', 'Enter the resulting revenue.', '€M', 8.5, 'Keep 85% of the starting revenue.'),
  ('profit-500k-margin-30-fixed-90', 'Operating profit', 1, 'Sales are €500k with a 30% contribution margin and €90k of fixed costs. What is operating profit?', 'Enter operating profit.', '€k', 60, 'Calculate contribution, then subtract fixed costs.'),
  ('profit-1m-variable-55-fixed-200', 'Operating profit', 2, 'Sales are €1M. Variable costs are 55% and fixed costs are €200k. What is operating profit?', 'Enter operating profit.', '€k', 250, 'The contribution margin is 45%.'),
  ('break-even-120k-40pct', 'Break-even', 1, 'Fixed costs are €120k and contribution margin is 40%. What revenue is needed to break even?', 'Enter break-even revenue.', '€k', 300, 'Divide fixed costs by the contribution margin.'),
  ('break-even-75k-25pct', 'Break-even', 1, 'Fixed costs are €75k and contribution margin is 25%. What revenue is needed to break even?', 'Enter break-even revenue.', '€k', 300, 'At 25%, every €4 of sales contributes €1.'),
  ('price-volume-100-5pct-10k', 'Pricing', 1, 'A product priced at €100 increases price by 5% and sells 10,000 units. What is the new revenue?', 'Enter total revenue.', '€k', 1050, 'Find the new unit price, then multiply by volume.'),
  ('price-volume-tradeoff', 'Pricing', 2, 'Price rises 10% from €50 while volume falls 5% from 20,000 units. What is the new revenue?', 'Enter total revenue.', '€k', 1045, 'New price is €55 and new volume is 19,000.'),
  ('discount-80-15pct', 'Pricing', 1, 'A product priced at €80 is discounted by 15%. What is the new price?', 'Enter the discounted price.', '€', 68, 'Keep 85% of the original price.'),
  ('gross-profit-15m-64pct', 'Margin impact', 1, 'Revenue is €15M at a 64% gross margin. What is gross profit?', 'Enter gross profit.', '€M', 9.6, 'Multiply revenue by the margin.'),
  ('margin-gain-3pts-12m', 'Margin impact', 1, 'Gross margin improves by 3 percentage points on €12M of revenue. How much gross profit is gained?', 'Enter the increase in gross profit.', '€M', 0.36, 'Apply 3% to revenue.'),
  ('margin-required-2m-on-8m', 'Margin impact', 1, 'A business needs €2M of gross profit on €8M of revenue. What gross margin is required?', 'Enter the margin percentage.', '%', 25, 'Divide gross profit by revenue.'),
  ('market-share-18-on-240', 'Market sizing', 1, 'A company has €18M of sales in a €240M market. What is its market share?', 'Enter the market share.', '%', 7.5, 'Divide company sales by total market size.'),
  ('market-size-12-share-8pct', 'Market sizing', 1, 'A company has €12M of sales and 8% market share. What is the total market size?', 'Enter total market size.', '€M', 150, 'Divide sales by 8%.'),
  ('customers-2m-arpu-400', 'Unit economics', 1, 'Annual revenue is €2M and annual revenue per customer is €400. How many customers are there?', 'Enter the customer count.', 'customers', 5000, 'Divide total revenue by revenue per customer.'),
  ('ltv-50-4pct-24', 'Unit economics', 2, 'Monthly revenue per customer is €50, gross margin is 80%, and average lifetime is 24 months. What is gross-profit LTV?', 'Enter gross-profit LTV.', '€', 960, 'Multiply monthly revenue by gross margin, then by lifetime.'),
  ('cac-payback-600-75', 'Unit economics', 1, 'Customer acquisition cost is €600 and monthly gross profit per customer is €75. What is CAC payback?', 'Enter the payback period.', 'months', 8, 'Divide CAC by monthly gross profit.'),
  ('runway-1m-125k', 'Cash runway', 1, 'Cash is €1M and monthly net burn is €125k. How many months of runway remain?', 'Enter runway.', 'months', 8, 'Divide cash by monthly burn.'),
  ('burn-900-to-660-12m', 'Cash runway', 2, 'Cash falls from €900k to €660k over 12 months. What is average monthly net burn?', 'Enter monthly burn.', '€k', 20, 'Find the cash reduction, then divide by 12.'),
  ('conversion-450-of-6000', 'Conversion', 1, '450 of 6,000 qualified leads become customers. What is the conversion rate?', 'Enter the conversion rate.', '%', 7.5, 'Divide customers by qualified leads.'),
  ('funnel-10k-30pct-20pct', 'Conversion', 2, 'A funnel has 10,000 visitors. 30% become leads and 20% of leads become customers. How many customers result?', 'Enter the customer count.', 'customers', 600, 'Calculate leads first, then customers.'),
  ('productivity-18-in-6h', 'Productivity', 1, 'A team completes 18 analyses in 6 hours. What is the hourly rate?', 'Enter analyses per hour.', 'per hour', 3, 'Divide output by hours.'),
  ('capacity-8-5-per-day-20days', 'Productivity', 1, 'Eight analysts complete 5 cases per day each for 20 working days. What is monthly capacity?', 'Enter total cases.', 'cases', 800, 'Multiply analysts, daily output, and working days.')
on conflict (slug) do update set
  category = excluded.category,
  difficulty = excluded.difficulty,
  prompt = excluded.prompt,
  instruction = excluded.instruction,
  unit = excluded.unit,
  correct_answer = excluded.correct_answer,
  hint = excluded.hint,
  is_active = true,
  updated_at = now();
